.travis.yml, package-lock.json, package.json, readme.md
New Feature: Travis & Heroku deployment
=> Deployment

server/db/models/order.js
Feature: Created Order Model for Database
=> feature: created order model

server/db/models/cart.js
=> feature: created cart model

package-lock.json, server/db/models/tea.js
Created Tea Model for Database.
=>  feature: created Tea Model

script/seed.js, server/db/models/index.js, server/db/models/orderProduct.js, server/db/models/user.js
feature: created associations and through-table to seed the database
=> feature: created associations and through table to seed the database

server/api/index.js, server/api/teas.js
=> feature: GET route for Teas

client/components/allTeas.js, client/routes.js, client/store/index.js, client/store/teas.js, client/store/user.js
feature: added allTeas component and path
=> feature: added allTeas component and path

server/api/cart.js, server/db/models/cart.js, server/db/models/cartProduct.js, server/db/models/index.js
created new Throughtable for cart-product and revised cart route so that we can pull the teaids for the products in our cart.
=>  feature: added CartProduct through-table and revised get cart route

server/api/teas.spec.js
feature: created failing test spec for teas GET route
=> feature: created failing test spec for teas GET route

server/api/cart.spec.js
Need to figure out how to make the get cart route spec include eager loading properly.
=> fix: eager loading aspect of get cart route

client/components/allTeas.js, client/components/index.js, client/components/singleTea.js, client/routes.js, client/store/cart.js, client/store/teas.js, server/api/teas.js
Created single teas component and add to cart function
=> Feature: Single Teas component and add to cart function

server/api/index.js, server/api/orders.js
Added GET order routes for order history
=> feature: added GET order routes

script/seed.js, server/db/models/index.js
Redefined Cart Model and Seed file so that Cart will have the UserID foreign key
=> Feature: Redefined Cart Model

server/api/orders.js
feature: order routes added for all orders and single order
=> feature: order routes added for all orders and single order

client/components/cart.js
feature: fixed shopping cart page to show general info of each product.
=> feature: shopping cart page

client/components/cart.js, client/store/cart.js, server/api/cart.js
feature: fixed cart page so that it has proper routes and actions.
=>  feature: fixed cart page route and actions

client/components/allTeas.js, client/components/cart.js, client/components/singleTea.js, client/components/user-home.js, client/routes.js, client/store/cart.js
unfinished feature: nonpersistent cart, working on making our cart display added items and qty.
=> unfinished feature: nonpersistent cart

client/components/checkoutForm.js, client/routes.js
I think I would like to add the checkoutForm as a prop inside of the checkout page component. I still need to build out the checkout page component too.
=> unfinished: not sure if my checkoutForm is fully fleshed out

client/routes.js, client/store/cart.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> git conflict

client/store/cart.js
feature: fixed cart reducer so that it is a hashtable
=> Fix reducers

client/components/allOrders.js, client/components/allTeas.js, client/components/cart.js, client/components/singleTea.js, server/api/orders.js, server/db/models/order.js
fix: merged cart and order routes
=> merged cart and order routes

script/seed.js, server/db/models/index.js
feature: New Seed File for our new schema design
=> feature: new Seed file - also removing former instances of cart

client/components/allTeas.js, client/components/navbar.js, server/api/index.js
Linked Name of Tea & Image to single Tea view
Also added general navigator routes to nav bar
=> feature: all teas component now is linked to single teas view

client/components/cart.js, client/store/cart.js
Updated CartReducer for Add to Cart functionality.
Updated Cart Component to display items added to cart & their quantity.
Added message when cart is empty.
=> Feature: Cart Reducer & Cart Component

server/auth/index.js
feature: added userId to the session at login
=> feature: add userId to the session

client/components/allOrders.js, client/components/navbar.js, client/routes.js, client/store/orders.js
feature: fixed order history for a user
=> feature: order history for user

client/components/checkout-page.js, client/routes.js
-need to remove bug - GET 404 (Not Found)
-Need to add mapstate and mapdispatch to shippingAddress form.
-Make sure order route is done and works so order summary can work
=> in-progress: need to get form and order summary to work

client/components/cart.js, client/components/navbar.js, client/components/singleTea.js, client/store/cart.js, client/store/orders.js, server/api/index.js, server/api/orderProducts.js, server/api/orders.js, server/db/models/order.js
Feature: Added Create Order Route and edited the singleTea component so that instances of order will be created each time someone adds to an EMPTY cart.
To do: 
Remove/destroy order when someone removes everything from their cart
Create OrderProduct on first add too
Update Order Products each time other time someone adds something to the cart (Cart QTY)
Update Order route (for status, email, address during checkout)
=> Orderroutes

server/api/orders.js
feature: wrote route to update Order for checkout page
=> update order route created

client/components/allTeas.js, client/components/cart.js, client/components/helperFuncs.js, client/components/singleTea.js
Features:
Created Price Calculation helperFunctions
Fixed Pricing on All Teas View, Single Teas View and Cart
=> feature: fixed prices and created calculation helperFuncs

client/components/shippingAddressForm.js, client/store/orders.js, server/api/orders.js
feature: PUT order route. pending to completed works. Tested on postman.
=> feature: PUT order route. pending to completed works

client/components/checkout-page.js, client/store/orders.js
Fixed routes for checkout page to show order
Fixed typo in order reducer
=>  fixed routes on checkout page and order reducer

server/api/orders.js
Fixed route for orders and profile page views
=> fixed route for orders/profile page

client/components/cart.js, client/store/cart.js, server/api/index.js, server/api/orderProduct.js
Feature: Increment button now shows changes in both database as well as redux state.
=> feature: increment button connects to db and redux

client/components/cart.js, client/store/cart.js, server/api/orderProduct.js
Feature: Decrement button now applies to both redux state as well as DB
Renamed action since it merged both increment and decrement into one.
=> Feature: Decrement

client/components/cart.js, client/store/cart.js, server/api/orderProduct.js, server/api/orders.js
Feature: Connected remove button to both db and redux cart
=> Feature: Remove

client/components/shippingAddressForm.js, client/payment-components/CheckoutForm.js, client/store/orders.js, package-lock.json, server/api/orders.js, server/payment-intent/server.js
feature: got shipping form to work and update from pending to complete
=> feature: got shipping form to work and update from pending to complete

client/components/singleOrder.js, client/store/orders.js, server/api/orders.js
Fixed the issue of single order not loading (API routes)
=> fixed: single order component

client/components/Confirmation.js, client/components/checkout-page.js, client/components/shippingAddressForm.js, client/components/singleTea.js, client/routes.js, client/store/cart.js, server/api/orders.js
=>  confirmation page redirection in progress

client/components/cart.js, client/components/checkout-page.js, client/components/singleTea.js, client/store/cart.js
Feature: Added Order total to checkout page
=> Added Total to Checkout Page

client/components/allOrders.js, package-lock.json, server/api/orders.js
fixed: Partially fixed the all orders component
=> fixed: Partially fixed the all orders component

client/components/navbar.js, client/store/index.js
Feature: Created root reducer to resetApp upon logout
(To Fix: For some reason cart is not being cleared...)
=> created root reducer to resetApp upon logout

server/api/orders.js, server/api/securityMiddleware/check-Auth.js
feature: new auth middleware 
needed: change route middlewares
=> feature: new auth middleware for users to access their own data

client/components/Confirmation.js, client/components/cart.js, client/components/checkout-page.js, client/components/shippingAddressForm.js, client/store/cart.js, server/api/orders.js
Feature:
Deleted redundant cart items array, loading page directly into componentDidMount
To Fix: 
Remove button does not sometimes does not reload page/refresh new cart
=> Feature: Deleted redundant cart items array

server/api/orderProduct.js, server/api/orders.js, server/api/teas.js, server/api/users.js
feature: added security middleware to the API routes
=> feature: added security middleware to the API routes

client/components/shippingAddressForm.js
Now able to click on shippingAddressForm button and get redirected to thank you page.
=> feature: redirect works on shippingAddressForm

client/components/Confirmation.js, client/components/checkout-page.js, client/components/shippingAddressForm.js, client/store/cart.js
Feature: fixed conflict with emptycart on confirmation page
=> Feature: fixed conflict with emptycart on confirmation page

client/components/Admin/adminAddTea.js, client/components/Admin/adminEditSingleTea.js, client/components/Admin/adminEditSingleUser.js
feature: redirect for admin buttons
=> feature: redirect for admin buttons

server/api/orderProduct.js
Feature: Refactored code for order products increment and decrement
=> Feature: Refactored code for order products increment and decrement

server/api/securityMiddleware/check-Auth.js
added res.redirect('/') to security middleware.
=> feature: security middleware redirects to home

client/components/cart.js, client/components/checkout-page.js, client/components/navbar.js, client/components/shippingAddressForm.js, client/components/singleTea.js, client/store/cart.js, server/api/orders.js
Features: 
Guest can now add to cart and check out (can't be marked as complete on the db though..)
Refactored the cart reducer code to simply the reducer cases.
=> Feature: Guest Cart

server/api/orderProduct.js, server/api/orders.js
fix: took out security routes to ensure guest chart functionality
=> fix: took out security routes to ensure guest chart functionality

client/components/checkout-page.js, client/components/shippingAddressForm.js, public/index.html, public/style.css
feature: fixed some spacing for checkout
=> feature: fixed some spacing for checkout

client/components/allOrders.js, client/components/user-home.js, client/components/userProfile.js, client/routes.js, public/style.css
feature: css for user homepage and some of user profile page
=> feature: css for user homepage and some of user profile page

client/components/allTeas.js, client/components/cart.js, client/components/singleTea.js, public/style.css
=> Feature: Cart CSS

client/components/allOrders.js, client/components/singleOrder.js, public/style.css
feature: CSS for Order History :)
=> feature: CSS for Order History

client/components/cart.js, client/components/checkout-page.js, client/components/shippingAddressForm.js, public/style.css
Feature: Added css to our checkout page.
=> Feature: CSS added to checkout page

client/components/checkout-page.js, public/style.css
Features: Added color change when add to cart button is hovered over. 
Added missing tag.
Fixed missing brace.
=> Feature: Button Hover

public/style.css
fix: minor fix of CSS on single item page
=> fix: minor fix of CSS on single item page

client/components/cart.js
Fix: plus minus button once and for all.
=> Fix: plus minus button once and for all.

client/components/Admin/adminAddTea.js, client/components/Admin/adminAllOrders.js, client/components/Admin/adminAllTeas.js, client/components/Admin/adminAllUsers.js, client/components/Admin/adminEditSingleTea.js, client/components/Admin/adminEditSingleUser.js, client/components/Admin/adminPage.js
feature: added logos to admin pages
=> feature: added logos to admin pages
